# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: forest
day_night: true
font: ''
font_size: L

# SEO

site_type: Organization
local_business_type: ''
org_name: ''
description: ''
twitter: ''

# Contact (edit or remove options as required)

email: trail@weblab.t.u-tokyo.ac.jp
appointment_url: 'https://calendly.com'
# contact_links:
#   - icon: comments
#     icon_pack: fas
#     name: Discuss on the forum
#     link: 'https://github.com/wowchemy/wowchemy-hugo-modules/discussions'

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: '2006/1/2'
time_format: '15:04'
address_format: zh

# Site features

highlight: true
highlight_languages: ['shell', 'bash', 'python', 'cpp', 'makefile']  # https://cdnjs.com/libraries/highlight.js
math: true
diagram: true
privacy_pack: false
edit_page:
  repo_url: 'https://github.com/matsuolab/roomba_hack'
  content_dir: 'textbook/content'
  repo_branch: 'master'
  editable:
    page: true
    post: true
    book: true
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: false
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  local_backend: false
icon:
  pack:
    ai: false
